### ISSUE TITLE
De-Esser slider doesn't save to whatever new value you set it (visual)

### ISSUE THREAD

**Issue by TheRealDadbeard** [GoXLR-on-Linux/goxlr-utility#132] opened 2023-11-11 15:09 UTC
So when you set a de-esser value and then swap between tabs (with or without saving) it will always show the value it started with. Internally it will set the correct value though.

I have to completely restart the app so it shows the correct one. This is on 1.0

**Comment by FrostyCoolSlug** [comment] 2023-11-13 15:36
Thanks for the report, I've managed to track this down and fixed it in [goxlr-ui#e3689263](https://github.com/GoXLR-on-Linux/goxlr-ui/commit/e36892635c24b25cae9032b39e81ba75e34ceb1e). Looks like it was also affecting the bleep volume, which I've fixed as well!

I'll put it into a 1.0.1 release at some point during the week, assuming no other issues are found.

**Comment by FrostyCoolSlug** [comment] 2023-11-30 00:02
Can you please grab the Windows artifact at the [bottom of this build](https://github.com/GoXLR-on-Linux/goxlr-utility/actions/runs/7039923106), install it and let me know if the problem is fixed?

Thanks.

**Comment by FrostyCoolSlug** [comment] 2023-12-30 23:34
Closing as Fixed.

**Closed by FrostyCoolSlug** 2023-12-30 23:34 UTC
