### ISSUE TITLE
GoXLR Utility will not run

### ISSUE THREAD

**Issue by Loko1956** [GoXLR-on-Linux/goxlr-utility#114] opened 2023-07-20 23:25 UTC
When I try to run the goxlr-utility-0.12.5.exe as administrator, I get an error saying "Unable to locate the GoXLR Driver, please ensure it is installed.
![Screenshot 2023-07-20 172317](https://github.com/GoXLR-on-Linux/goxlr-utility/assets/140113784/a5e9054b-c010-4000-ad76-eeb6aeb8bf45)

**Comment by FrostyCoolSlug** [comment] 2023-07-20 23:51
So a couple of questions, 
1) Does the official app work without issues?
2) Are you running a 32bit or 64bit OS?
3) If you open Regedit and navigate to `HKEY_CLASSES_ROOT\CLSID\{024D0372-641F-4B7B-8140-F4DFE458C982}\InprocServer32\` - Do you see the API driver present?
4) Is your driver installed to the Default Location?

Hopefully these will help track down this issue.

Thanks

**Comment by Loko1956** [comment] 2023-07-20 23:57
Thanks for your reply.
1. Yes except I have to manually connect to my stream deck recently
2. 64bit
3. Yes, it is there.  D:\Program Files\TC-HELICON\GoXLR_Audio_Driver\W 10_x64\goxlr_x64.dll
4. No, I have it in my D: drive

**Comment by FrostyCoolSlug** [comment] 2023-07-21 00:00
Ok thanks.

You're the second person to report this issue in the last couple of hours, which is wild.

Unfortunately, you may not be able to use the util until the next release, I'm going to need to investigate why having the drivers installed to a different drive is causing issues. I'll keep you updated though.

**Comment by Loko1956** [comment] 2023-07-21 00:00
Awesome!

Thank you so much

**Comment by FrostyCoolSlug** [comment] 2023-07-21 00:37
Ok I've found the cause, fixed it and generated a test build, could you please download the following:

https://github.com/GoXLR-on-Linux/goxlr-utility/suites/14458134804/artifacts/816440585

And give that installer a try please?

Technical explaination: when the installer runs the first thing it does is check for some registry keys to see if you've installed before. If any of those flag as an 'error', it'll fall back to defaults during the installation (which is good, and desired behaviour). The problem happening here was that those errors simply weren't being cleared, so when it went to do the 'where's the driver?' check, it found the driver, but was picking up the previous errors and failing the check. This build corrects that error.

**Comment by Loko1956** [comment] 2023-07-21 00:41
Sorry, same result

**Comment by FrostyCoolSlug** [comment] 2023-07-21 00:43
Damn, was rushing for a fix.. Fair enough, I'll take a closer look at this tomorrow and see if I can work out what's going on.

**Comment by Loko1956** [comment] 2023-07-21 00:46
No worries.   Thanks for trying.   My GoXLR is working so no immediate rush.

**Comment by FrostyCoolSlug** [comment] 2023-07-21 00:47
Just reviewing your responses to the first questionairre, can you confirm the path on point 3 please? I don't know if github mangled it (please wrap it in \` tags, so it looks `like this`)..

**Comment by Loko1956** [comment] 2023-07-21 00:49
(D:\Program Files\TC-HELICON\GoXLR_Audio_Driver\W 10_x64\goxlr_x64.dll)

**Comment by FrostyCoolSlug** [comment] 2023-07-21 00:50
Something may be wrong with your driver install, the path I would expect to see is: `D:\Program Files\TC-HELICON\GoXLR_Audio_Driver\W10_x64\goxlr_audioapi_x64.dll`

**Comment by Loko1956** [comment] 2023-07-21 00:53
'HKEY_CLASSES_ROOT\CLSID\{024D0372-641F-4B7B-8140-F4DFE458C982}\InprocServer32'

**Comment by FrostyCoolSlug** [comment] 2023-07-21 00:54
Could you provide me with a screenshot of the contents of `D:\Program Files\TC-HELICON\GoXLR_Audio_Driver\W10_x64` please?

**Comment by Loko1956** [comment] 2023-07-21 00:54
Yes, that is right.  I left out the _ between W10 and x64.... sorry

**Comment by FrostyCoolSlug** [comment] 2023-07-21 00:55
ok, I'm also seeing github mangling things, all good, I'll do some additional testing this side :)

**Comment by Loko1956** [comment] 2023-07-21 00:55
Thank you for your time

**Comment by FrostyCoolSlug** [comment] 2023-07-21 01:05
No problem, I've got a new build underway, should be able to send it out shortly :)

**Comment by Loko1956** [comment] 2023-07-21 01:08
Great!

**Comment by FrostyCoolSlug** [comment] 2023-07-21 01:33
Could you give this build a try please:

https://github.com/GoXLR-on-Linux/goxlr-utility/suites/14458873098/artifacts/816496452

**Comment by Loko1956** [comment] 2023-07-21 01:38
Absolutely

**Comment by Loko1956** [comment] 2023-07-21 01:39
i\It worky!!!   So far anyways

**Comment by Loko1956** [comment] 2023-07-21 01:39
Should I put it in C: or D:?

**Comment by FrostyCoolSlug** [comment] 2023-07-21 01:39
Put it wherever you want :)

**Comment by Loko1956** [comment] 2023-07-21 01:39
lol

**Comment by Loko1956** [comment] 2023-07-21 01:40
Run utility on startup or use app insted?

**Comment by FrostyCoolSlug** [comment] 2023-07-21 01:41
You can choose both, I'd recommend running it on startup (although you'll need to disable the official app), and the exeperimental app just makes it run in it's own window, instead of a browser (which a lot of people prefer!)

**Comment by Loko1956** [comment] 2023-07-21 01:50
Can I change it from browser to experimental app in the settings?   I think I would prefer that over the browser too

**Comment by FrostyCoolSlug** [comment] 2023-07-21 01:51
Currently there's not a quick switch, but you should be able to re-run the installer and tick the box which will set it up

**Comment by FrostyCoolSlug** [comment] 2023-07-21 01:55
Let me know if everything is good, so I can close this issue as solved :)

**Comment by Loko1956** [comment] 2023-07-21 01:56
Seems to work great.  I just need to bring over my old profiles and presets and samples

**Comment by FrostyCoolSlug** [comment] 2023-07-21 01:57
Should be simple enough, right click on the tray icon and you can open the relevant util paths, then just grab stuff from the official app (Documents/GoXLR), and you should be good :)

**Comment by Loko1956** [comment] 2023-07-21 01:58
Thank you so much!   I appreciate your time and effort.

**Comment by FrostyCoolSlug** [comment] 2023-07-21 01:59
No problem, thanks for the detailed reports and switft responses that have helpped with tracking this down, it's very much appreciated. I hope you're able to get everything working right :)

**Closed by FrostyCoolSlug** 2023-07-21 01:59 UTC

**Comment by Loko1956** [comment] 2023-07-21 02:01
Do the "Recover Defaults" buttons work?

**Comment by FrostyCoolSlug** [comment] 2023-07-21 02:02
They do, but they wont overwrite existing files, you'll need to remove the default profiles / mic profiles prior to pressing them.

**Comment by Loko1956** [comment] 2023-07-21 02:21
Got it all set up.  I did it the hard way and drug all my old files into the utility.   Works great!
"Truely you are a wizard"

**Comment by Chaosjan44** [comment] 2023-08-05 08:15
I had the same issue, got it working by creating the path where the driver normally sits manually and reinstalling it to that directory
