### ISSUE TITLE
GoXLR App's GUI won't open

### ISSUE THREAD

**Issue by misterpyrrhuloxia** [GoXLR-on-Linux/goxlr-utility#162] opened 2024-04-11 19:52 UTC
I just installed the latest available version of the utility. During installation, I set the `UI Handler` to `Browser`. I then started up the utility from the start menu (I'm on Windows 11). Then in the browser-based utility I changed the setting `System` > `Utility Settings` > `UI Handler` from `Browser` to `App`.  
Then I closed the utility from the system tray and re-launched the utility again from the start menu. But the App never launches. The utility is visible in the system tray, but the App's window never opened. I then tried to right-click on the system tray icon > `Configure GoXLR` and yet the App never opened or became visible. So I re-opened the browser-based utility and changed the `UI Handler` back to `Browser`.

Does anyone have any clue as to why the XLR App itself won't open while I have the `UI Handler` enabled?

**Comment by FrostyCoolSlug** [comment] 2024-04-11 19:58
Did the app work fine with the previous version of the utility?

**Comment by FrostyCoolSlug** [comment] 2024-04-11 20:26
I've been able to reproduce the problem (although it seems to be wildly inconsistent), I've re-released the 1.1.0 installer with a fix for the problem. Could you redownload the installer from [here](https://github.com/GoXLR-on-Linux/goxlr-utility/releases/tag/v1.1.0), reinstall, then give it another try please?

**Comment by Noctunus** [comment] 2024-04-12 22:40
I guess that's the reason why the v1.1.0 vanished from the releases?

Btw the winget release is still there and when using wingetui it regularly tries to install the version which is not there. Just wanted to mention that - maybe while the v1.1 is being revised it would be better to also remove the winget version to reduce confusion on this end.

**Comment by FrostyCoolSlug** [comment] 2024-04-12 23:18
You're correct, due to this issue (which ended up being more widespread than originally thought), 1.1.0 has been pulled until it can be solved.

We have a PR open with winget to remove the version from there, but we're waiting for acceptance:

https://github.com/microsoft/winget-pkgs/pull/148856

**Comment by FrostyCoolSlug** [comment] 2024-04-13 13:01
Back to the original issue, 1.1.1 has been released which contains a fix for this problem. It should all work properly again now.

Thanks!

**Comment by FrostyCoolSlug** [comment] 2024-04-14 17:32
Closing as complete.

**Comment by misterpyrrhuloxia** [comment] 2024-04-16 01:17
@FrostyCoolSlug, thanks for looking into this. I just updated from version 1.1.0 to 1.1.1. During installation I set the UI Handler to Browser. After installation, I opened launched GoXLR-Utility, opened the utility in the browser, went to the settings, and changed the UI Handler from Browser to App. Then I completely closed GoXLR-Utility from the system tray, confirmed that both `goxlr-utility-ui.exe` and `goxlr-daemon.exe` had both stopped, and then launched the utility again from the start menu. the utility started in the system tray but the utility's App GUI never opened. I then right-clicked the system tray icon and clicked `Configure GoXLR` but still nothing happened. I then went back into the Browser GUI to make sure that the UI Handler setting was still set to App and it was.

So by all appearances, the upgrade from version 1.1.0 to 1.1.1 made no difference at all for me.

**Comment by FrostyCoolSlug** [comment] 2024-04-16 01:35
Ok, I'll reopen this.. do you have a regular install of Windows, or have you run a tool that strips out various features (often referred to as 'bloat')?

**Comment by misterpyrrhuloxia** [comment] 2024-04-16 01:54
The only thing I've done to de-bloat is forcefully remove Edge and Edge Webview (or something like that). I used [CrystalIdea's Uninstall Tool](https://crystalidea.com/uninstall-tool) to do so.

**Comment by FrostyCoolSlug** [comment] 2024-04-16 02:05
That's unfortunate, the Utility's app uses Webview to render the UI. There are two reasons for this decision:

1) Using a browser that's expected to be present on an OS removes the need to bundle one with the Utility, massively reducing file size..

2) Important security updates (as well as performance improvements) are handled with OS updates, saving the need to have to repeatedly issue utility releases to keep things up-to-date.

Unfortunately there's really nothing I can do to fix this that would result in a satisfactory conclusion, as a single Dev the overheads and management of bundeling and managing a browser to display the interface are just too high.

Given that Edge (or at least) WebView are 'expected' components of Windows, I can't really support edge cases where people are forcefully removing them.

Sorry I couldn't give a better answer.

**Comment by misterpyrrhuloxia** [comment] 2024-04-16 03:21
> I can't really support **`edge`** cases where people are forcefully removing them.

No pun intended?🤣
I understand, though. Thank you for your help, sir.🫡

**Comment by misterpyrrhuloxia** [comment] 2024-04-16 06:37
Do you think you'd consider adding a notice to the main Readme stating that Webview is a requirement if one desires to use the app on Windows?

**Comment by misterpyrrhuloxia** [comment] 2024-04-16 08:24
I manually reinstalled Webview2 and now the GoXLR Utility's App gui works perfectly. Thanks for your help!

**Comment by FrostyCoolSlug** [comment] 2024-07-04 23:01
> Do you think you'd consider adding a notice to the main Readme stating that Webview is a requirement if one desires to use the app on Windows?

I honestly don't think that's necessary. Webview is a required, and default, component of Windows. I consider people removing it as people who are intentionally breaking their Windows installation, and it's ultimately not my responsibility to make sure they don't do that. People running tools which remove critical components from their windows installation should do so with the understanding that it may cause problems with certain applications, which in this case it does.

The utility installer tries to install Webview2 as part of the process, so these tools are not only removing webview, but leaving it flagged as installed, preventing the installer's attempt to fix it from correctly running.

This isn't my problem, and I don't intend on making it my problem, so closing this as complete.

**Closed by FrostyCoolSlug** 2024-07-04 23:01 UTC
