### ISSUE TITLE
Recorded and manually added samples play at different volumes. 

### ISSUE THREAD

**Issue by IamGreen112** [GoXLR-on-Linux/goxlr-utility#119] opened 2023-08-09 00:14 UTC
I'm unsure if this is a bug or not but any files I manually add to the sampler play at a much higher volume level than samples I've recorded. I noticed this while trying to move certain sounds to a single button but whenever I manually add a sample it sounds way too loud even if it's something I recorded with the sampler. 

Here's an example video I recorded. [https://www.youtube.com/watch?v=mJVILS2DiQI](url)

**Comment by FrostyCoolSlug** [comment] 2023-08-14 16:47
This is the same behaviour as the official app, Samples which are added go through an [EBU R 128](https://en.wikipedia.org/wiki/EBU_R_128) pass to normalize them to 'broadcast' level, however, to avoid the additional overhead or calculating the levels 'live', samples which are being recorded do not. If you remove the recording, and re-add it, in both the official App and the Util, it'll be normalised in the same way.

In the future, I'll be looking into options to configure / change this behaviour somewhat, although I've not created a list of options for it yet. For now though, this is working as intended (even if a little obscure).

**Comment by IamGreen112** [comment] 2023-08-15 11:48
Cheers for the insight! It's a bit weird and annoying to deal with but I'm glad to hear that you'll be looking into things though.

**Comment by FrostyCoolSlug** [comment] 2023-11-30 05:09
So I've made some changes to how the utility handles Samples for the upcoming v1.0.1 release.

Samples recorded by holding a button will now receive the same gain calculations as a sample which is manually added, do quieter recordings will be boosted up to correct level.

In addition, I've added what can only be described as a Volume 'Override' slider to Samples, which allow for manual adjustments if the calculations are off.

Could you grab the windows articaft at the bottom of [this build](https://github.com/GoXLR-on-Linux/goxlr-utility/actions/runs/7042197677), which contains the changes and give them a test?

Thanks

**Comment by FrostyCoolSlug** [comment] 2023-12-30 23:34
Closing as Fixed.

**Closed by FrostyCoolSlug** 2023-12-30 23:34 UTC
