### ISSUE TITLE
No audio profiles available and thus no outputs available

### ISSUE THREAD

**Issue by RyderForReal** [GoXLR-on-Linux/goxlr-utility#34] opened 2022-09-22 15:57 UTC
Distro: Arch Linux, kernel 5.19.10-zen1-1-zen (so keep in mind that this could have nothing to do with the GoXLR daemon as Arch has a tendency of doing interesting things at interesting times)
DE: KDE (X11)
Full-size GoXLR (USB passthrough)
Daemon v. 0.4.0
Audio control via KDE Settings

Everything worked perfectly until a system update about 3-4 days ago, at which point audio output completely stopped working. I checked KDE Settings and am unable to select any audio profiles (and thus none of the GoXLR outputs register). The daemon works fine in the sense that I can control the device without any issues.

**Troubleshooting steps attempted:**
Pacman reinstall of pipewire, pipewire-pulse, wireplumber, pipewire-jack, pipewire-alsa, etc. - Didn't work, tried reinstall with -Rsc on second try, also didn't fix the issue
Tried pipewire-media-session, didn't work
Checked for updates and updated, didn't work
Tried to build goxlr-utility from source, didn't fix the issue

This could be a PipeWire problem since I can control my device just fine. On the other hand, other audio outputs show up and have available profiles.

**Comment by FrostyCoolSlug** [comment] 2022-09-22 17:53
This was a bug introduced with the latest kernel, and should be fixed with the next release, check out https://bugzilla.kernel.org/show_bug.cgi?id=216500 for details.

**Comment by cmoro-deusto** [comment] 2022-09-23 07:54
Just in case helps somebody else, the bug was introduced in version 5.19.9. As of today, only workaround is to rollback to 5.19.8. I can also confirm it occurs in bare metal kernel, not only in -zen.

**Comment by FrostyCoolSlug** [comment] 2022-09-25 21:54
Currently not fixed in 5.19.10, looks like the fix will be going into 5.19.11 instead.

**Comment by pwae** [comment] 2022-09-30 12:02
reports in upstream that this made it into 5.9.12 - this is available in unstable on Manjaro - waiting for it to reach unstable myself to test.

**Comment by FrostyCoolSlug** [comment] 2022-09-30 12:27
I've had reports on discord that it's working again in 5.9.12, I'll await your confirmation though, and will double check the latest 5.15 release as well.

**Comment by cmoro-deusto** [comment] 2022-10-01 09:34
If it helps, I can confirm is working again in 5.19.12

**Comment by FrostyCoolSlug** [comment] 2022-10-04 15:55
Lots of reports that everything is working again under 5.19.12 (thanks @cmoro-deusto and the various peoples on discord), so I'm going to close this as 'fixed'.

**Closed by FrostyCoolSlug** 2022-10-04 15:55 UTC
