### ISSUE TITLE
No GoXLR Devices Found

### ISSUE THREAD

**Issue by TheRedHerring95** [GoXLR-on-Linux/goxlr-utility#172] opened 2024-06-16 06:07 UTC
Not sure if I've missed a step somewhere, or if I've missed an already sorted issue, but I've taken a look and been unable to find anything that seems to provide guidance on this. 

I've got both a GoXLR Mini and a full sized GoXLR, and have been unable to get either showing up in the utility. Levels adjust as expected, at least on the full sized (haven't tested that on the Mini yet) running the newest firmware, and the Mini powers up, both show in Audio with their individual channels. 

Pipewire with Pulse appears to be the default on my OS, and I was unable to see whether this is likely to be what that caused, or if there's something else that may be the cause; I'm slowly working through getting it set up to know what I need to do to swap into my main system, but I'm still gradually working my way through figuring some things out.

Running on NixOS, with the following being all I can find regarding my sound configuration so far
```
# Enable sound with pipewire.
  sound.enable = true;
  hardware.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    # If you want to use JACK applications, uncomment this
    jack.enable = true;
```

Not sure what else may be needed or useful, but if there's anything else me know.

**Comment by FrostyCoolSlug** [comment] 2024-06-16 15:06
Could you provide the log files and let me know how you installed the utility? If I were to guess, the udev rules for the GoXLR are missing.

**Comment by TheRedHerring95** [comment] 2024-06-17 07:26
Thanks for the quick response, unfortunately it was just as I got to bed so I couldn't respond earlier. 

I'd love to provide the logs, but could you specify which ones? I'd hate to provide ones that aren't useful, and I'm still a little green to Linux to know which handle what. 

As for how I installed it, I installed it through the NixOS configuration file. Any advice for how to check the udev rules? I think I saw something while going through previous issues posted about it, but my attempts to run the copy through `sudo cp 50-goxlr.rules /etc/udev/rules.d/50-goxlr.rules && sudo udevadm control --reload-rules && sudo udevadm trigger` failed with `cp: cannot stat '50-goxlr.rules': No such file or directory`; I'm assuming I'm just running it in the wrong place, but I'm not sure where the right place would be. 

Sorry if these seem like stupid or basic questions, I'm still working on picking things up as quickly as I can.

**Comment by FrostyCoolSlug** [comment] 2024-06-24 16:54
The Nix package for the GoXLR Utility is managed by a third party, so it's a little tricky to help support there (I'm personally not a Nix user), but I'll give @Sporesirius and @errnoh a ping (sorry!), as they were responsible for getting the package sorted there.

For the logs, they're available in `~/.local/share/goxlr-utility/logs/`, the latest `goxlr-daemon.log` may provide insight.

**Comment by errnoh** [comment] 2024-06-24 18:22
Thanks for the ping @FrostyCoolSlug 

I'm using the latest version from Nix so "works on my machine", but lets see if I can help with debugging. If nothing else, at least I might be able to rubberduck.

So for the relevant background:
- the `50-goxlr.rules` are inside the packages etc/udev/rules.d directory as per https://github.com/nixos/nixpkgs/blob/master/pkgs/tools/audio/goxlr-utility/default.nix#L47
- the rules are installed on this line: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/audio/goxlr-utility.nix#L33 which installs all rules in `«pkg»/etc/udev/rules.d and «pkg»/lib/udev/rules.d`

If it worked correctly should be able to see the file installed at `/etc/udev/rules.d/50-goxlr.rules`, if not, maybe you don't have `services.goxlr-utility.enable = true;` set?

After confirming that my next question would be about your overall setup. `goxlr-utility` is using XDG autostart, a feature which I hadn't run into before I added this nix package (but that has worked really well so no complaints there), what I don't know is if XDG autostart has some requirements from the system itself (maybe @FrostyCoolSlug  knows more about that part?). Anyways, if that ends up being the issue back when I created the module I added `services.goxlr-utility.autoStart.xdg` option that can be disabled in case someone wants to run it manually or using some other method they desire.

**Comment by errnoh** [comment] 2024-06-27 12:52
@TheRedHerring95 did you resolve your issue?

**Comment by TheRedHerring95** [comment] 2024-06-27 13:27
Sorry, it's been a busy few days at work and I haven't had the chance to jump on my laptop and test this again since your suggestions and guidance. Only one more day till the weekend, so hopefully I'll be able to get back to troubleshooting it in the next day or so. 

I appreciate you checking whether I'd solved it though; as much as I like to think I'll jump straight on and confirm it's working with just what it was, I acknowledge that there's definitely a chance I'd get side tracked and end up not getting the comment added with just what happened to get everything working.

**Comment by Different-Name** [comment] 2024-06-28 05:16
I am also having this issue - also on NixOS

`goxlr-daemon.log` showed the following error repeated:
`[ERROR] Couldn't load potential GoXLR on bus 1 address 2: Access denied (insufficient permissions)`
Am I perhaps missing a group on my user?

**Comment by errnoh** [comment] 2024-06-29 15:33
@TheRedHerring95 no worries, just wanted to make sure there's nothing wrong with the package that I'd need to fix :) and to make sure that the issue gets sorted out within decent time.

@Different-Name this does also look like it's due to missing udev rules. Check my message above ( https://github.com/GoXLR-on-Linux/goxlr-utility/issues/172#issuecomment-2187155379 ) and ensure you have the goxlr utilities module enabled.

**Comment by Different-Name** [comment] 2024-06-29 15:36
@errnoh sorry I forgot to mention I checked the rules were in place, the file was indeed there. I have the module enabled

**Comment by errnoh** [comment] 2024-06-29 17:01
@Different-Name hmm, weird. Assuming the contents of `/etc/udev/rules.d/50-goxlr.rules` also match https://github.com/GoXLR-on-Linux/goxlr-utility/blob/main/50-goxlr.rules then the next steps in debugging would probably be:

- ensure you have restarted since installing, just to be sure
- maybe `sudo udevadm control --reload-rules && sudo udevadm trigger` or similar, though if you have restarted this seems unlikely to be required
- re-connect the GoXLR device itself, there could be some initialization that needs to happen but also requires the rules, so attaching the device _after_ rules are already in effect might result in problem being solved.

But do report back even if that doesn't help, the `Access denied (insufficient permissions)` just seems like quite generic udev error that _should_ be fixed with just turning things on and off in correct order :sweat:

**Comment by Different-Name** [comment] 2024-06-29 17:04
To continue the trend I'm unfortunately not going to have access to my goxlr for the next week 🥲

I'll double check and get back to you when I can - thank you

**Comment by TheRedHerring95** [comment] 2024-07-05 06:40
Hi @errnoh, sorry for the delay in checking back in; life's thrown a few curve balls in the last couple of weeks, so I didn't end up having the chance last weekend to take a look. 

I do bare good news though; I didn't have it enabled, and rebuilding with that line you'd mentioned seems to have resolved the issue. I did have an issue at first where it didn't pick up if the device was already connected when I launched the utility, but that appears to be working fine now as well. 

I've only tested on the Mini at this point, but will confirm everything is operating as expected on the full sized unit tonight and let you know if there's any complications. 

Let me know if there's any additional checking I can do to compare between myself and @Different-Name as well, in case we can identify the difference and what may be causing mine to now work with that additional line while theirs is still having issues.

**Comment by Different-Name** [comment] 2024-07-05 06:45
I assume my issue is because I did not reboot, the udev rules only apply when a device is connected while the system is running, so that's probably the issue I encountered. Always reboot!

Will update when I can though

**Comment by TheRedHerring95** [comment] 2024-07-05 06:48
Huh, interesting; I didn't reboot for mine; just ran the rebuild switch command and went with testing. Had to restart the utility with the device not connected, but after that it seemed solid on my end. Definitely worth a shot though! Good luck :slightly_smiling_face:

**Comment by Different-Name** [comment] 2024-07-07 07:06
After a reboot, it is working as intended

**Comment by errnoh** [comment] 2024-07-09 11:23
Glad to hear it solved the issue :) 

I'm not sure if there's some good way to signal NixOS users if there's a module that's supposed to be used instead of just installing the package. While I could submit a PR in this repo to guide people how to enable the service on NixOS I don't want to burden @FrostyCoolSlug with NixOS related questions when it's not an "officially" supported version, but at the same time I wouldn't be surprised to see this being asked again in the future.

Anyways, @TheRedHerring95 or @FrostyCoolSlug based on the above comments (i.e. both managing to get the service running properly) I'd say that this GH issue can be closed!

**Closed** 2024-07-09 11:36 UTC

**Comment by Different-Name** [comment] 2024-07-26 05:06
> It's definitely possible to disable direct usage of a package, I saw it done a couple of days ago while I was looking through the nixpkgs repo, though I was not able to find it again doing a quick search.

Found it, not sure if it helps though

https://github.com/NixOS/nixpkgs/blob/dc14ed91132ee3a26255d01d8fd0c1f5bff27b2f/pkgs/by-name/pr/proton-ge-bin/package.nix#L24-L26
